/* ═══════════════════════════════════════════════════════════
   TYPEFLUX — Prose Passages
   Real, everyday English — the sentences a hand actually writes
   on a working day. Business correspondence and plain talk, set
   as short coherent passages rather than disjoint lines.
   ═══════════════════════════════════════════════════════════ */

const SENTENCES = {
    // Corporate / working correspondence — email, meetings, the desk.
    business: [
        "I reviewed the proposal before lunch, and the remaining questions are listed at the top of the thread.",
        "Please review the invoice when the new estimate arrives; the sections that need a decision are already marked.",
        "The team revised the risk list, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the forecast once procurement responds, so no one is surprised during the handoff.",
        "The manager found one issue in the legal comment, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; support will update the expense file and send a clean version before the handoff call.",
        "The meeting can stay short if everyone reads the renewal form first and brings only the decisions that need discussion.",
        "The work is waiting on the change request, but the rest can continue without blocking the team.",
        "The vendor organized the timeline because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the reviewer will compare the support ticket against the notes and send any gaps after the finance check.",
        "The client asked for a clearer summary, so the analyst noted the delivery window with the risks in plain language.",
        "If the numbers still look right once the contract is countersigned, the coordinator can treat the product brief as ready for signoff.",
        "The designer confirmed the release memo after the last comment is addressed, and the remaining questions are listed at the top of the thread.",
        "Please review the status update once the vendor replies; the sections that need a decision are already marked.",
        "The lead tested the scope document, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the proposal before the manager returns, so no one is surprised during the handoff.",
        "The account owner found one issue in the invoice, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the risk list first and brings only the decisions that need discussion.",
        "The work is waiting on the forecast, but the rest can continue without blocking the team.",
        "The sales desk drafted the legal comment because the deadline moved and the old assumptions no longer hold.",
        "Before the call, legal will compare the expense file against the notes and send any gaps after the finance check.",
        "The client asked for a clearer summary, so the product owner queued the renewal form with the risks in plain language.",
        "If the numbers still look right after the data export finishes, the help desk can treat the change request as ready for signoff.",
        "The implementation group reviewed the timeline before it goes to the client, and the remaining questions are listed at the top of the thread.",
        "Please review the support ticket before the next planning session; the sections that need a decision are already marked.",
        "The finance lead revised the delivery window, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the product brief after the reviewer finishes, so no one is surprised during the handoff.",
        "The account team found one issue in the release memo, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; procurement will update the status update and send a clean version after the morning call.",
        "The meeting can stay short if everyone reads the scope document first and brings only the decisions that need discussion.",
        "The work is waiting on the proposal, but the rest can continue without blocking the team.",
        "The planning desk organized the invoice because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the delivery team will compare the risk list against the notes and send any gaps after the workshop ends.",
        "The client asked for a clearer summary, so the executive sponsor noted the forecast with the risks in plain language.",
        "The documentation owner signed the legal comment once the numbers settle, and the remaining questions are listed at the top of the thread.",
        "Please review the expense file before the next planning session; the sections that need a decision are already marked.",
        "The release manager attached the renewal form, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the change request once the release note is ready, so no one is surprised during the handoff.",
        "The vendor contact found one issue in the timeline, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the workshop host will update the support ticket and send a clean version before lunch.",
        "The meeting can stay short if everyone reads the delivery window first and brings only the decisions that need discussion.",
        "The work is waiting on the product brief, but the rest can continue without blocking the team.",
        "The team collected the release memo because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the client will compare the status update against the notes and send any gaps when the support queue clears.",
        "The client asked for a clearer summary, so the manager mapped the scope document with the risks in plain language.",
        "If the numbers still look right once the numbers settle, support can treat the proposal as ready for signoff.",
        "Finance updated the invoice when the dashboard refreshes, and the remaining questions are listed at the top of the thread.",
        "Please review the risk list once the blockers are clear; the sections that need a decision are already marked.",
        "The vendor approved the forecast, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the legal comment before the invoice is sent, so no one is surprised during the handoff.",
        "The analyst found one issue in the expense file, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the renewal form first and brings only the decisions that need discussion.",
        "The work is waiting on the change request, but the rest can continue without blocking the team.",
        "The engineer audited the timeline because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the lead will compare the support ticket against the notes and send any gaps before the manager returns.",
        "The client asked for a clearer summary, so the partner verified the delivery window with the risks in plain language.",
        "If the numbers still look right ahead of the review, the account owner can treat the product brief as ready for signoff.",
        "The project group signed the release memo after support confirms the fix, and the remaining questions are listed at the top of the thread.",
        "Please review the status update after the training session; the sections that need a decision are already marked.",
        "The sales desk attached the scope document, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the proposal before the invoice is sent, so no one is surprised during the handoff.",
        "The product owner found one issue in the invoice, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the help desk will update the risk list and send a clean version after the last comment is addressed.",
        "The meeting can stay short if everyone reads the forecast first and brings only the decisions that need discussion.",
        "The work is waiting on the legal comment, but the rest can continue without blocking the team.",
        "The finance lead collected the expense file because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the service desk will compare the renewal form against the notes and send any gaps once the issue is reproduced.",
        "The client asked for a clearer summary, so the account team mapped the change request with the risks in plain language.",
        "Procurement filed the timeline before the wider team sees it, and the remaining questions are listed at the top of the thread.",
        "Please review the support ticket when the final data comes in; the sections that need a decision are already marked.",
        "The analyst group shared the delivery window, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the product brief once the timeline is adjusted, so no one is surprised during the handoff.",
        "The delivery team found one issue in the release memo, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the executive sponsor will update the status update and send a clean version before it goes to the client.",
        "The meeting can stay short if everyone reads the scope document first and brings only the decisions that need discussion.",
        "The work is waiting on the proposal, but the rest can continue without blocking the team.",
        "The release manager drafted the invoice because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the support lead will compare the risk list against the notes and send any gaps after the checklist is signed.",
        "The client asked for a clearer summary, so the vendor contact queued the forecast with the risks in plain language.",
        "If the numbers still look right once legal signs off, the workshop host can treat the legal comment as ready for signoff.",
        "I reviewed the expense file when the final data comes in, and the remaining questions are listed at the top of the thread.",
        "Please review the renewal form when the draft is approved; the sections that need a decision are already marked.",
        "The team revised the change request, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the timeline when the pilot group replies, so no one is surprised during the handoff.",
        "The manager found one issue in the support ticket, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the delivery window first and brings only the decisions that need discussion.",
        "The work is waiting on the product brief, but the rest can continue without blocking the team.",
        "Operations compared the release memo because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the vendor will compare the status update against the notes and send any gaps when the client confirms scope.",
        "The client asked for a clearer summary, so the reviewer priced the scope document with the risks in plain language.",
        "If the numbers still look right once legal signs off, the analyst can treat the proposal as ready for signoff.",
        "The coordinator filed the invoice before Friday afternoon, and the remaining questions are listed at the top of the thread.",
        "Please review the risk list before the agenda closes; the sections that need a decision are already marked.",
        "The engineer shared the forecast, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the legal comment before the handoff call, so no one is surprised during the handoff.",
        "The partner found one issue in the expense file, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the account owner will update the renewal form and send a clean version when the dashboard refreshes.",
        "The meeting can stay short if everyone reads the change request first and brings only the decisions that need discussion.",
        "The work is waiting on the timeline, but the rest can continue without blocking the team.",
        "The sales desk drafted the support ticket because the deadline moved and the old assumptions no longer hold.",
        "Before the call, legal will compare the delivery window against the notes and send any gaps before lunch.",
        "The client asked for a clearer summary, so the product owner queued the product brief with the risks in plain language.",
        "The help desk balanced the release memo after the file is uploaded, and the remaining questions are listed at the top of the thread.",
        "Please review the status update once procurement responds; the sections that need a decision are already marked.",
        "The regional office scheduled the scope document, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the proposal before the handoff call, so no one is surprised during the handoff.",
        "The service desk found one issue in the invoice, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the account team will update the risk list and send a clean version after support confirms the fix.",
        "The meeting can stay short if everyone reads the forecast first and brings only the decisions that need discussion.",
        "The work is waiting on the legal comment, but the rest can continue without blocking the team.",
        "The analyst group audited the expense file because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the planning desk will compare the renewal form against the notes and send any gaps once the contract is countersigned.",
        "The client asked for a clearer summary, so the delivery team verified the change request with the risks in plain language.",
        "If the numbers still look right once the vendor replies, the executive sponsor can treat the timeline as ready for signoff.",
        "The documentation owner signed the support ticket after the customer meeting, and the remaining questions are listed at the top of the thread.",
        "Please review the delivery window before the manager returns; the sections that need a decision are already marked.",
        "The release manager attached the product brief, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the release memo by the end of the day, so no one is surprised during the handoff.",
        "The vendor contact found one issue in the status update, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the scope document first and brings only the decisions that need discussion.",
        "The work is waiting on the proposal, but the rest can continue without blocking the team.",
        "We reopened the invoice because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the team will compare the risk list against the notes and send any gaps after the data export finishes.",
        "The client asked for a clearer summary, so the client expanded the forecast with the risks in plain language.",
        "If the numbers still look right before the next planning session, the manager can treat the legal comment as ready for signoff.",
        "Support balanced the expense file after the customer meeting, and the remaining questions are listed at the top of the thread.",
        "Please review the renewal form after the reviewer finishes; the sections that need a decision are already marked.",
        "Operations scheduled the change request, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the timeline after the morning call, so no one is surprised during the handoff.",
        "The reviewer found one issue in the support ticket, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the analyst will update the delivery window and send a clean version when the final data comes in.",
        "The meeting can stay short if everyone reads the product brief first and brings only the decisions that need discussion.",
        "The work is waiting on the release memo, but the rest can continue without blocking the team.",
        "The engineer audited the status update because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the lead will compare the scope document against the notes and send any gaps once the numbers settle.",
        "The client asked for a clearer summary, so the partner verified the proposal with the risks in plain language.",
        "The account owner explained the invoice before the launch window opens, and the remaining questions are listed at the top of the thread.",
        "Please review the risk list once the release note is ready; the sections that need a decision are already marked.",
        "The training team flagged the forecast, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the legal comment before lunch, so no one is surprised during the handoff.",
        "Legal found one issue in the expense file, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the product owner will update the renewal form and send a clean version before Friday afternoon.",
        "The meeting can stay short if everyone reads the change request first and brings only the decisions that need discussion.",
        "The work is waiting on the timeline, but the rest can continue without blocking the team.",
        "The regional office compared the support ticket because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the finance lead will compare the delivery window against the notes and send any gaps once the numbers settle.",
        "The client asked for a clearer summary, so the service desk priced the product brief with the risks in plain language.",
        "If the numbers still look right once the blockers are clear, the account team can treat the release memo as ready for signoff.",
        "Procurement filed the status update before the next sprint starts, and the remaining questions are listed at the top of the thread.",
        "Please review the scope document before the invoice is sent; the sections that need a decision are already marked.",
        "The analyst group shared the proposal, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the invoice when the new estimate arrives, so no one is surprised during the handoff.",
        "The delivery team found one issue in the risk list, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the forecast first and brings only the decisions that need discussion.",
        "The work is waiting on the legal comment, but the rest can continue without blocking the team.",
        "The customer success team closed the expense file because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the release manager will compare the renewal form against the notes and send any gaps ahead of the review.",
        "The client asked for a clearer summary, so the support lead trimmed the change request with the risks in plain language.",
        "If the numbers still look right after the training session, the vendor contact can treat the timeline as ready for signoff.",
        "The workshop host explained the support ticket after the finance check, and the remaining questions are listed at the top of the thread.",
        "Please review the delivery window before the invoice is sent; the sections that need a decision are already marked.",
        "We flagged the product brief, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the release memo after the last comment is addressed, so no one is surprised during the handoff.",
        "The client found one issue in the status update, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the manager will update the scope document and send a clean version after the customer meeting.",
        "The meeting can stay short if everyone reads the proposal first and brings only the decisions that need discussion.",
        "The work is waiting on the invoice, but the rest can continue without blocking the team.",
        "Operations compared the risk list because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the vendor will compare the forecast against the notes and send any gaps before the wider team sees it.",
        "The client asked for a clearer summary, so the reviewer priced the legal comment with the risks in plain language.",
        "The analyst noted the expense file after the finance check, and the remaining questions are listed at the top of the thread.",
        "Please review the renewal form once the timeline is adjusted; the sections that need a decision are already marked.",
        "The designer confirmed the change request, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the timeline before it goes to the client, so no one is surprised during the handoff.",
        "The lead found one issue in the support ticket, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the partner will update the delivery window and send a clean version after the customer meeting.",
        "The meeting can stay short if everyone reads the product brief first and brings only the decisions that need discussion.",
        "The work is waiting on the release memo, but the rest can continue without blocking the team.",
        "The training team reopened the status update because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the sales desk will compare the scope document against the notes and send any gaps once legal signs off.",
        "The client asked for a clearer summary, so legal expanded the proposal with the risks in plain language.",
        "If the numbers still look right when the draft is approved, the product owner can treat the invoice as ready for signoff.",
        "The help desk balanced the risk list after the workshop ends, and the remaining questions are listed at the top of the thread.",
        "Please review the forecast when the pilot group replies; the sections that need a decision are already marked.",
        "The regional office scheduled the legal comment, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the expense file before the next planning session, so no one is surprised during the handoff.",
        "The service desk found one issue in the renewal form, but it should be easy to resolve once the owner confirms the detail.",
        "The meeting can stay short if everyone reads the change request first and brings only the decisions that need discussion.",
        "The work is waiting on the timeline, but the rest can continue without blocking the team.",
        "The operations manager assigned the support ticket because the deadline moved and the old assumptions no longer hold.",
        "Before the call, the analyst group will compare the delivery window against the notes and send any gaps once legal signs off.",
        "The client asked for a clearer summary, so the planning desk organized the product brief with the risks in plain language.",
        "If the numbers still look right before the agenda closes, the delivery team can treat the release memo as ready for signoff.",
        "The executive sponsor noted the status update when the support queue clears, and the remaining questions are listed at the top of the thread.",
        "Please review the scope document before the handoff call; the sections that need a decision are already marked.",
        "The customer success team confirmed the proposal, then added a short note explaining what changed and why it matters.",
        "The next step is to align on the invoice when the dashboard refreshes, so no one is surprised during the handoff.",
        "The support lead found one issue in the risk list, but it should be easy to resolve once the owner confirms the detail.",
        "Thanks for the quick response; the vendor contact will update the forecast and send a clean version before the next sprint starts.",
        "The meeting can stay short if everyone reads the legal comment first and brings only the decisions that need discussion.",
        "Thanks for getting back to me so quickly. I have looked over the proposal and most of it works for our team. Can we set up a short call tomorrow to go through the last few points?",
        "Just a quick heads up that the meeting has been moved to three o'clock. I know that is short notice, so let me know if the new time does not work for you and we can find another slot.",
        "I wanted to follow up on the report we discussed last week. The numbers look solid, but I think we should add a section on the risks before we send it to the client.",
        "Please find the updated budget attached. I have flagged the two line items that went over, and I am happy to walk through them whenever you have a few minutes.",
        "Great work on the presentation today. The client seemed genuinely interested, and they asked some good questions. Let us regroup in the morning to plan our next steps.",
        "I am running about ten minutes late for the standup. Please go ahead and start without me, and I will catch up on anything I miss when I join.",
        "Could you send me the latest version of the slide deck before lunch? I want to review it once more before we share it with the wider team.",
        "We appreciate your patience while we sorted out the shipping issue. Your order is now on its way, and you should receive a tracking number within the next hour.",
        "The new hire starts on Monday, so we should make sure her laptop and accounts are ready by Friday. Can you check with the support team and confirm?",
        "I think we are spending too much time in meetings this quarter. Let us try to keep them shorter and only invite the people who really need to be there.",
        "Thanks again for your feedback on the draft. I have made most of the changes you suggested, and I left a couple of comments where I had a question.",
        "The deadline is tight, but I believe we can make it if we focus on the core features first. We can always add the smaller extras in a later release.",
        "Let me know if you need anything else from me before the review. I am out of the office on Thursday, but I will be checking my email in the afternoon.",
        "Our quarterly results came in above target, which is great news for the whole team. I want to thank everyone for the hard work and the long hours.",
        "I have scheduled the training session for next Wednesday at ten. It should take about an hour, and there will be time for questions at the end.",
        "Please remember to submit your expense reports by the end of the month. If any of your receipts are missing, reach out to the finance team as soon as you can.",
        "The customer raised a fair point about our delivery times. We should look at the process and see if there is a way to make it faster without raising costs.",
        "I am attaching the notes from this morning so everyone is on the same page. If I missed anything important, please reply to the thread and add it.",
        "We have decided to push the launch back by two weeks. This gives us more time to test the product and fix the bugs that came up in the last review.",
        "Welcome to the team. Your first week will be mostly meetings and setup, so do not worry about getting much done. Ask plenty of questions while everything is still new."
    ],

    // Plain, day to day talk — the kind of thing you actually say.
    everyday: [
        "I picked up the groceries before the rain started, and the whole day felt a little easier after that.",
        "We meant to handle the keys earlier, but it finally got done while the kettle boiled.",
        "It was nice to have the birthday card ready when the street got busy, especially after the week had been so full.",
        "The kids laughed about the travel bag, then told the story twice more before anyone left.",
        "The plan changed before the errands started, so our neighbor kept it simple and saved the lunch boxes for later.",
        "My friend put the tomato plants by the door so it would not be forgotten in the morning.",
        "Everyone slowed down on the way home, and even the window screens seemed less urgent for a while.",
        "Mom did not need much, just the hallway shelf, a quiet room, and a little time to breathe.",
        "The family checked a good book twice after the appointment, then decided it was good enough to leave alone.",
        "The house felt calmer before the guests knocked, especially after my brother finally dealt with the movie tickets.",
        "Nobody made a big deal of it, but the group handling the front room changed the mood of the evening.",
        "Everyone promised to bring the winter coat next time, since it would have helped when the morning finally slowed.",
        "My roommate found the picnic blanket during the quiet part of the afternoon, and the whole day felt a little easier after that.",
        "The guests meant to handle the blue sweater earlier, but it finally got done before the weekend filled up.",
        "It was nice to have the school forms ready before the bus came, especially after the week had been so full.",
        "The teacher laughed about the groceries, then told the story twice more before anyone left.",
        "The plan changed once the traffic cleared, so the couple next door kept it simple and saved the keys for later.",
        "Everyone slowed down this morning, and even the birthday card seemed less urgent for a while.",
        "My cousin did not need much, just the travel bag, a quiet room, and a little time to breathe.",
        "The cashier checked the lunch boxes twice before bedtime, then decided it was good enough to leave alone.",
        "The house felt calmer before the guests knocked, especially after my aunt finally dealt with the tomato plants.",
        "Nobody made a big deal of it, but the babysitter handling the window screens changed the mood of the evening.",
        "The coach promised to bring the hallway shelf next time, since it would have helped after the last box was unpacked.",
        "The landlord picked up a good book after the phone call, and the whole day felt a little easier after that.",
        "The new neighbor meant to handle the movie tickets earlier, but it finally got done after the store opened.",
        "It was nice to have the front room ready before the bus came, especially after the week had been so full.",
        "My old friend laughed about the winter coat, then told the story twice more before anyone left.",
        "The plan changed after the first cup of coffee, so the delivery driver kept it simple and saved the picnic blanket for later.",
        "The nurse put the blue sweater by the door so it would not be forgotten in the morning.",
        "Everyone slowed down before everyone arrived, and even the school forms seemed less urgent for a while.",
        "My uncle did not need much, just the groceries, a quiet room, and a little time to breathe.",
        "The grandparents checked the keys twice once the baby fell asleep, then decided it was good enough to leave alone.",
        "The house felt calmer after the dishes were done, especially after the little one finally dealt with the birthday card.",
        "Nobody made a big deal of it, but the house handling the travel bag changed the mood of the evening.",
        "The kitchen brought the lunch boxes before dinner, and the whole day felt a little easier after that.",
        "The bus driver meant to handle the tomato plants earlier, but it finally got done after the store opened.",
        "It was nice to have the window screens ready as the evening settled, especially after the week had been so full.",
        "The mechanic laughed about the hallway shelf, then told the story twice more before anyone left.",
        "The plan changed when the lights flickered, so the visitors kept it simple and saved a good book for later.",
        "The shop owner put the movie tickets by the door so it would not be forgotten in the morning.",
        "Everyone slowed down before everyone arrived, and even the front room seemed less urgent for a while.",
        "We did not need much, just the winter coat, a quiet room, and a little time to breathe.",
        "My sister checked the picnic blanket twice while the windows were open, then decided it was good enough to leave alone.",
        "The house felt calmer once the music stopped, especially after the kids finally dealt with the blue sweater.",
        "Nobody made a big deal of it, but our neighbor handling the school forms changed the mood of the evening.",
        "My friend promised to bring the groceries next time, since it would have helped before dinner.",
        "Dad forgot the keys during lunch, and the whole day felt a little easier after that.",
        "Mom meant to handle the birthday card earlier, but it finally got done while the bread cooled.",
        "It was nice to have the travel bag ready during the slow walk home, especially after the week had been so full.",
        "My brother laughed about the lunch boxes, then told the story twice more before anyone left.",
        "The plan changed before the rain started, so the group kept it simple and saved the tomato plants for later.",
        "Everyone slowed down while the kettle boiled, and even the window screens seemed less urgent for a while.",
        "My roommate did not need much, just the hallway shelf, a quiet room, and a little time to breathe.",
        "The guests checked a good book twice after the game ended, then decided it was good enough to leave alone.",
        "The house felt calmer before the errands started, especially after the driver finally dealt with the movie tickets.",
        "Nobody made a big deal of it, but the teacher handling the front room changed the mood of the evening.",
        "The couple next door promised to bring the winter coat next time, since it would have helped on the way home.",
        "The repair person brought the picnic blanket once the sun came out, and the whole day felt a little easier after that.",
        "My cousin meant to handle the blue sweater earlier, but it finally got done after the appointment.",
        "It was nice to have the school forms ready before the guests knocked, especially after the week had been so full.",
        "My aunt laughed about the groceries, then told the story twice more before anyone left.",
        "The plan changed when the morning finally slowed, so the babysitter kept it simple and saved the keys for later.",
        "The coach put the birthday card by the door so it would not be forgotten in the morning.",
        "Everyone slowed down before the weekend filled up, and even the travel bag seemed less urgent for a while.",
        "The new neighbor did not need much, just the lunch boxes, a quiet room, and a little time to breathe.",
        "The whole class checked the tomato plants twice before the errands started, then decided it was good enough to leave alone.",
        "The house felt calmer once the traffic cleared, especially after my old friend finally dealt with the window screens.",
        "Nobody made a big deal of it, but the delivery driver handling the hallway shelf changed the mood of the evening.",
        "The nurse replaced a good book after the long drive, and the whole day felt a little easier after that.",
        "The barista meant to handle the movie tickets earlier, but it finally got done before bedtime.",
        "It was nice to have the front room ready before the guests knocked, especially after the week had been so full.",
        "The grandparents laughed about the winter coat, then told the story twice more before anyone left.",
        "The plan changed after the last box was unpacked, so the little one kept it simple and saved the picnic blanket for later.",
        "The house put the blue sweater by the door so it would not be forgotten in the morning.",
        "Everyone slowed down after the store opened, and even the school forms seemed less urgent for a while.",
        "The bus driver did not need much, just the groceries, a quiet room, and a little time to breathe.",
        "The librarian checked the keys twice when the clouds broke, then decided it was good enough to leave alone.",
        "The house felt calmer after the first cup of coffee, especially after the mechanic finally dealt with the birthday card.",
        "Nobody made a big deal of it, but the visitors handling the travel bag changed the mood of the evening.",
        "The shop owner promised to bring the lunch boxes next time, since it would have helped before everyone arrived.",
        "I picked up the tomato plants before bedtime, and the whole day felt a little easier after that.",
        "We meant to handle the window screens earlier, but it finally got done once the baby fell asleep.",
        "It was nice to have the hallway shelf ready after the dishes were done, especially after the week had been so full.",
        "The kids laughed about a good book, then told the story twice more before anyone left.",
        "The plan changed before dinner, so our neighbor kept it simple and saved the movie tickets for later.",
        "Everyone slowed down after the store opened, and even the front room seemed less urgent for a while.",
        "Dad did not need much, just the winter coat, a quiet room, and a little time to breathe.",
        "Mom checked the picnic blanket twice after the movie finished, then decided it was good enough to leave alone.",
        "The house felt calmer when the lights flickered, especially after the family finally dealt with the blue sweater.",
        "Nobody made a big deal of it, but my brother handling the school forms changed the mood of the evening.",
        "The group promised to bring the groceries next time, since it would have helped before everyone arrived.",
        "Everyone replaced the keys once the house was quiet, and the whole day felt a little easier after that.",
        "My roommate meant to handle the birthday card earlier, but it finally got done while the windows were open.",
        "It was nice to have the travel bag ready once the music stopped, especially after the week had been so full.",
        "The driver laughed about the lunch boxes, then told the story twice more before anyone left.",
        "The plan changed before dinner, so the teacher kept it simple and saved the tomato plants for later.",
        "The couple next door put the window screens by the door so it would not be forgotten in the morning.",
        "Everyone slowed down while the bread cooled, and even the hallway shelf seemed less urgent for a while.",
        "My cousin did not need much, just a good book, a quiet room, and a little time to breathe.",
        "The cashier checked the movie tickets twice before the garden dried out, then decided it was good enough to leave alone.",
        "The house felt calmer before the rain started, especially after my aunt finally dealt with the front room.",
        "Nobody made a big deal of it, but the babysitter handling the winter coat changed the mood of the evening.",
        "The coach polished the picnic blanket when the street got busy, and the whole day felt a little easier after that.",
        "The landlord meant to handle the blue sweater earlier, but it finally got done after the game ended.",
        "It was nice to have the school forms ready before the errands started, especially after the week had been so full.",
        "The whole class laughed about the groceries, then told the story twice more before anyone left.",
        "The plan changed on the way home, so my old friend kept it simple and saved the keys for later.",
        "The delivery driver put the birthday card by the door so it would not be forgotten in the morning.",
        "Everyone slowed down after the appointment, and even the travel bag seemed less urgent for a while.",
        "The barista did not need much, just the lunch boxes, a quiet room, and a little time to breathe.",
        "My uncle checked the tomato plants twice before the garden dried out, then decided it was good enough to leave alone.",
        "The house felt calmer when the morning finally slowed, especially after the grandparents finally dealt with the window screens.",
        "Nobody made a big deal of it, but the little one handling the hallway shelf changed the mood of the evening.",
        "The house promised to bring a good book next time, since it would have helped before the weekend filled up.",
        "The kitchen brought the movie tickets before the bus came, and the whole day felt a little easier after that.",
        "The bus driver meant to handle the front room earlier, but it finally got done before the errands started.",
        "It was nice to have the winter coat ready once the traffic cleared, especially after the week had been so full.",
        "The mechanic laughed about the picnic blanket, then told the story twice more before anyone left.",
        "The plan changed after the long drive, so the visitors kept it simple and saved the blue sweater for later.",
        "Everyone slowed down before bedtime, and even the school forms seemed less urgent for a while.",
        "I did not need much, just the groceries, a quiet room, and a little time to breathe.",
        "We checked the keys twice while the soup simmered, then decided it was good enough to leave alone.",
        "The house felt calmer after the last box was unpacked, especially after my sister finally dealt with the birthday card.",
        "Nobody made a big deal of it, but the kids handling the travel bag changed the mood of the evening.",
        "Our neighbor promised to bring the lunch boxes next time, since it would have helped after the store opened.",
        "My friend polished the tomato plants before the bus came, and the whole day felt a little easier after that.",
        "Dad meant to handle the window screens earlier, but it finally got done when the clouds broke.",
        "It was nice to have the hallway shelf ready after the first cup of coffee, especially after the week had been so full.",
        "The family laughed about a good book, then told the story twice more before anyone left.",
        "The plan changed before everyone arrived, so my brother kept it simple and saved the movie tickets for later.",
        "The group put the front room by the door so it would not be forgotten in the morning.",
        "Everyone slowed down once the baby fell asleep, and even the winter coat seemed less urgent for a while.",
        "My roommate did not need much, just the picnic blanket, a quiet room, and a little time to breathe.",
        "The guests checked the blue sweater twice as the room warmed up, then decided it was good enough to leave alone.",
        "The house felt calmer before dinner, especially after the driver finally dealt with the school forms.",
        "Nobody made a big deal of it, but the teacher handling the groceries changed the mood of the evening.",
        "The couple next door stirred the keys as the evening settled, and the whole day felt a little easier after that.",
        "The repair person meant to handle the birthday card earlier, but it finally got done after the movie finished.",
        "It was nice to have the travel bag ready when the lights flickered, especially after the week had been so full.",
        "The cashier laughed about the lunch boxes, then told the story twice more before anyone left.",
        "The plan changed before everyone arrived, so my aunt kept it simple and saved the tomato plants for later.",
        "The babysitter put the window screens by the door so it would not be forgotten in the morning.",
        "Everyone slowed down while the windows were open, and even the hallway shelf seemed less urgent for a while.",
        "The landlord did not need much, just a good book, a quiet room, and a little time to breathe.",
        "The new neighbor checked the movie tickets twice before the library closed, then decided it was good enough to leave alone.",
        "The house felt calmer before dinner, especially after the whole class finally dealt with the front room.",
        "Nobody made a big deal of it, but my old friend handling the winter coat changed the mood of the evening.",
        "The delivery driver promised to bring the picnic blanket next time, since it would have helped while the bread cooled.",
        "The nurse replaced the blue sweater during the slow walk home, and the whole day felt a little easier after that.",
        "The barista meant to handle the school forms earlier, but it finally got done before the garden dried out.",
        "It was nice to have the groceries ready before the rain started, especially after the week had been so full.",
        "The grandparents laughed about the keys, then told the story twice more before anyone left.",
        "The plan changed when the street got busy, so the little one kept it simple and saved the birthday card for later.",
        "Everyone slowed down after the game ended, and even the travel bag seemed less urgent for a while.",
        "The kitchen did not need much, just the lunch boxes, a quiet room, and a little time to breathe.",
        "The bus driver checked the tomato plants twice before the library closed, then decided it was good enough to leave alone.",
        "The house felt calmer on the way home, especially after the librarian finally dealt with the window screens.",
        "Nobody made a big deal of it, but the mechanic handling the hallway shelf changed the mood of the evening.",
        "The visitors promised to bring a good book next time, since it would have helped after the appointment.",
        "The shop owner stirred the movie tickets before the guests knocked, and the whole day felt a little easier after that.",
        "I meant to handle the front room earlier, but it finally got done before the garden dried out.",
        "It was nice to have the winter coat ready when the morning finally slowed, especially after the week had been so full.",
        "My sister laughed about the picnic blanket, then told the story twice more before anyone left.",
        "The plan changed before the weekend filled up, so the kids kept it simple and saved the blue sweater for later.",
        "Our neighbor put the school forms by the door so it would not be forgotten in the morning.",
        "Everyone slowed down before the errands started, and even the groceries seemed less urgent for a while.",
        "Dad did not need much, just the keys, a quiet room, and a little time to breathe.",
        "Mom checked the birthday card twice this morning, then decided it was good enough to leave alone.",
        "The house felt calmer after the long drive, especially after the family finally dealt with the travel bag.",
        "Nobody made a big deal of it, but my brother handling the lunch boxes changed the mood of the evening.",
        "The group counted the tomato plants before the guests knocked, and the whole day felt a little easier after that.",
        "Everyone meant to handle the window screens earlier, but it finally got done while the soup simmered.",
        "It was nice to have the hallway shelf ready after the last box was unpacked, especially after the week had been so full.",
        "The guests laughed about a good book, then told the story twice more before anyone left.",
        "The plan changed after the store opened, so the driver kept it simple and saved the movie tickets for later.",
        "The teacher put the front room by the door so it would not be forgotten in the morning.",
        "Everyone slowed down when the clouds broke, and even the winter coat seemed less urgent for a while.",
        "The repair person did not need much, just the picnic blanket, a quiet room, and a little time to breathe.",
        "My cousin checked the blue sweater twice after work, then decided it was good enough to leave alone.",
        "The house felt calmer before everyone arrived, especially after the cashier finally dealt with the school forms.",
        "Nobody made a big deal of it, but my aunt handling the groceries changed the mood of the evening.",
        "The babysitter promised to bring the keys next time, since it would have helped once the baby fell asleep.",
        "The coach polished the birthday card after the dishes were done, and the whole day felt a little easier after that.",
        "The landlord meant to handle the travel bag earlier, but it finally got done as the room warmed up.",
        "It was nice to have the lunch boxes ready before dinner, especially after the week had been so full.",
        "The whole class laughed about the tomato plants, then told the story twice more before anyone left.",
        "The plan changed as the evening settled, so my old friend kept it simple and saved the window screens for later.",
        "Everyone slowed down after the movie finished, and even the hallway shelf seemed less urgent for a while.",
        "The nurse did not need much, just a good book, a quiet room, and a little time to breathe.",
        "The barista checked the movie tickets twice before the rain started, then decided it was good enough to leave alone.",
        "The house felt calmer before everyone arrived, especially after my uncle finally dealt with the front room.",
        "Nobody made a big deal of it, but the grandparents handling the winter coat changed the mood of the evening.",
        "The little one promised to bring the picnic blanket next time, since it would have helped while the windows were open.",
        "The house counted the blue sweater once the music stopped, and the whole day felt a little easier after that.",
        "The kitchen meant to handle the school forms earlier, but it finally got done before the library closed.",
        "It was nice to have the groceries ready before dinner, especially after the week had been so full.",
        "The librarian laughed about the keys, then told the story twice more before anyone left.",
        "The plan changed while the bread cooled, so the mechanic kept it simple and saved the birthday card for later.",
        "The visitors put the travel bag by the door so it would not be forgotten in the morning.",
        "Everyone slowed down before the garden dried out, and even the lunch boxes seemed less urgent for a while.",
        "I was thinking we could try that new place down the street for dinner tonight. I have heard good things about it, and it would be nice to get out of the house for a while.",
        "Do not forget to pick up milk and bread on your way home. The store closes early on Sundays, so you might want to leave a little sooner than usual.",
        "The weather has been so strange this week. It was warm and sunny yesterday, and now it looks like it might rain all afternoon. I never know what to wear.",
        "I finally finished the book you lent me, and I really enjoyed it. The ending caught me by surprise. Let me know if you have any others I should read.",
        "We should plan something for the weekend before it fills up. Maybe a hike if the weather is nice, or we could just stay in and watch a few movies.",
        "Thank you so much for helping me move last weekend. I could not have done it without you. Let me buy you lunch sometime soon to say thanks.",
        "My phone has been acting up all day. The battery drains so fast now, and half the apps freeze when I open them. I think it might be time for a new one.",
        "The kids have been asking to go to the park all morning. If the rain holds off, I will take them after lunch so they can burn off some energy.",
        "I tried that recipe you sent me, and it turned out really well. I added a little extra garlic because we like it, and everyone went back for seconds.",
        "Traffic was terrible on the way in this morning. There was an accident on the main road, so I had to take the long way around and still ended up late.",
        "Let us catch up properly soon. It feels like it has been months since we had a real conversation. Are you free for a coffee sometime next week?",
        "I have been trying to get to bed earlier, but it is harder than it sounds. There is always one more thing to do, and then it is already past midnight.",
        "The garden is finally starting to look the way I wanted. The tomatoes are coming in nicely, and the flowers we planted in spring are blooming all at once.",
        "I am not sure what to get my brother for his birthday. He says he does not want anything, but I would still like to find him a small surprise.",
        "We ran out of coffee this morning, and you would think the world had ended. I will grab some on the way home so tomorrow goes a little more smoothly.",
        "It was so good to see everyone last night. We stayed up far too late talking, but it was worth it. We really should do that more often.",
        "I keep meaning to call the doctor and book that appointment. I will do it first thing tomorrow, before I get caught up in everything else and forget again.",
        "The dog has way too much energy today. He has been pacing by the door for an hour, so I think a long walk after dinner is the only thing that will help.",
        "I cleaned out the closet this afternoon and found things I had not seen in years. It is amazing how much you can hold on to without ever noticing.",
        "Let me know when you are close and I will start the kettle. There is no rush at all, so take your time and drive safely if the roads are still wet."
    ]
};

// Prose passage utilities — mirrors QuoteGenerator's shape so the
// app can treat a passage like any other body of text.
const SentenceGenerator = {
    all() {
        return [...SENTENCES.business, ...SENTENCES.everyday];
    },

    // Return one coherent passage at random.
    getAny() {
        const pool = this.all();
        return { text: pool[Math.floor(Math.random() * pool.length)] };
    },

    // Build a body of prose of roughly `targetWords` words by joining
    // distinct passages until the target is met. At least one passage
    // is always returned, so a small target still yields real text.
    getPassage(targetWords = 25) {
        const pool = this.all();
        const picked = [];
        const used = new Set();
        let count = 0;
        while ((count < targetWords || picked.length === 0) && used.size < pool.length) {
            const i = Math.floor(Math.random() * pool.length);
            if (used.has(i)) continue;
            used.add(i);
            picked.push(pool[i]);
            count += pool[i].split(/\s+/).length;
        }
        return { text: picked.join(' ') };
    }
};
